Fixes for v1.4 (Issues 196, 165)
AY2324S2-CS2103T-W09-4/tp pull request #204
Opened 2024-04-13 15:47 UTC by rahhulleee

Close #196
Close #165

2024-04-13 16:13 UTC, youdonnnn approved these changes
lgtm!

2024-04-14 03:42 UTC, irwynliong requested changes
please re commit

2024-04-14 03:42 UTC, irwynliong commented on src/main/java/seedu/address/model/person/Name.java
> +            + "and it should be no more than 20 characters";
no more than 40 characters

2024-04-14 04:04 UTC, jimseah-0116 commented on src/main/java/seedu/address/model/person/Name.java
> +            + "and it should be no more than 20 characters";
I'll fix it, no worries

2024-04-14 04:27 UTC, irwynliong approved these changes

2024-04-14 04:27 UTC, merged